pipeline{
    agent any

    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/xalt0/Evaluacion1_TINGESO']])
                dir("karting-frontend"){
                    bat "npm install --legacy-peer-deps"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("karting-frontend") {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                            bat """
                                echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                                docker build -t vtamdev/karting-frontend .
                                docker push vtamdev/karting-frontend
                            """
                        }
                    }
                }
            }
        }
    }
}