server:
  port: ${SERVER_PORT:8085}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DBNAME:groupDiscounts}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
