apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-frontend-deployment
  labels:
    app: payroll-frontend-deployment
spec:
  selector:
    matchLabels:
      app: payroll-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: payroll-frontend-deployment
    spec:
      containers:
        - name: payroll-frontend
          image: vtamdev/frontend-ms:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: payroll-frontend-service
  labels:
    app: payroll-frontend
spec:
  selector:
    app: payroll-frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer